[General]
network = src.FiveGNetwork
sim-time-limit = 200s
scheduler-class = "omnetpp::cRealTimeScheduler"

# --- Chemins ---
ned-path = ../src:../../simu5g-1.4.1/src:../../inet-4.5.4/src

# --- Config Réseau ---
*.configurator.typename = "Ipv4NetworkConfigurator"
*.configurator.addDefaultRoutes = true


# ---------------------------------------------------------------------------
# BLINDAGE TOTAL ANTI-DIALOGUE ET ANTI-PORT (L'OPTION FINALE)
# ---------------------------------------------------------------------------
# IDs Réseau (Bloque les pop-ups MasterId)
**.masterId = 1
**.macCellId = 1
**.nrMasterId = 1
**.nrMacCellId = 1

# Paramètres de Mobilité (Bloque les pop-ups Z, StdDev, et Marges)
**.initialZ = 0m
**.mobility.initFromDisplayString = false
**.mobility.updateInterval = 0.01s
**.constraintAreaMinX = 0m
**.constraintAreaMaxX = 1000m
**.constraintAreaMinY = 0m
**.constraintAreaMaxY = 1000m
**.constraintAreaMinZ = 0m
**.constraintAreaMaxZ = 100m
**.speedStdDev = 0mps
**.angleStdDev = 0deg
**.alpha = 0.5
**.margin = 10m

*.server.app[*].localPort = -1
*.ue[*].app[0].localPort = 1000
**.destPort = 1000

**.startTime = 0.1s
**.stopTime = -1s

[Config Statistics]
**.channelModel = "UMA"
**.pathlossModel = "P3GPP38901"
**.transmitter.power = 0.01W
**.cellularNic.phy.receiver.noiseFigure = 5dB


# ---------------------------------------------------------------------------
# VARIATIONS POUR L'APPRENTISSAGE DU GNN (Généralisation)
# ---------------------------------------------------------------------------

# --- 1. Variation du Scheduling (La stratégie de l'antenne) ---
# OMNeT++ va tester successivement ces 3 politiques
**.gnb[*].nic.phy.transmitter.power = 0.01W

# MAXCI , DRR , PF
**.gnb[*].cellularNic.mac.schedulingDisciplineDl = "PF"
**.gnb[*].cellularNic.mac.schedulingDisciplineUl = ${sched}
**.gnb[*].cellularNic.numBands = 50

**.rlc.um.queueSize = 100KiB
**.mac.queueSize = 100KiB


# ---------------------------------------------------------------------------
# CONFIGURATION DU SCÉNARIO 20 UEs
# ---------------------------------------------------------------------------
[Config DT-Scenario]
extends = Statistics

*.numUe = 15
*.numGnb = 1


*.dtConnector.numMobilityModules = 16
*.dtConnector.samplingInterval = 0.1s
*.dtConnector.mobilityModulePaths = "ue[0].mobility,ue[1].mobility,ue[2].mobility,ue[3].mobility,ue[4].mobility,ue[5].mobility,ue[6].mobility,ue[7].mobility,ue[8].mobility,ue[9].mobility,ue[10].mobility,ue[11].mobility,ue[12].mobility,ue[13].mobility,ue[14].mobility,gnb[0].mobility"


# --- CONFIGURATION DES PROFILS DE TRAFIC (Varier le Throughput) ---

*.server.numApps = 15
*.ue[*].numApps = 1
*.ue[*].app[0].typename = "UdpSink"
*.server.app[*].typename = "UdpBasicApp"
**.destPort = 1000


*.gnb[0].mobility.initialX = 500m
*.gnb[0].mobility.initialY = 500m
*.gnb[0].mobility.initialZ = 30m 

*.server.app[0..11].destAddresses = "ue[" + string(ancestorIndex(0)) + "]"
*.server.app[0..11].messageLength = 1450B
*.server.app[0..11].sendInterval = uniform(0.0005s, 0.001s)   # 0.5ms = Stress total
*.ue[0..11].mobility.typename = "GaussMarkovMobility"
*.ue[0..11].mobility.speed = uniform(10mps, 30mps)



# --- PERTURBATION 1 : L'UE URLLC (UE 12) ---
# Petit paquet, intervalle fixe, doit être protégé par le scheduler
*.server.app[12].destAddresses = "ue[12]"
*.server.app[12].messageLength = intuniform(200B, 400B)
*.server.app[12].sendInterval = 10ms
*.ue[12].mobility.typename = "StationaryMobility"
*.ue[12].mobility.initialX = 510m
*.ue[12].mobility.initialY = 510m


# --- PERTURBATION 2 : LE CAPTEUR IoT (UE 13) ---
# Presque pas de trafic, pour voir si le GNN le traite bien
*.server.app[13].destAddresses = "ue[13]"
*.server.app[13].messageLength = intuniform(50B, 90B)
*.server.app[13].sendInterval = 500ms
*.ue[13].mobility.typename = "LinearMobility"
*.ue[13].mobility.speed = 1mps

# --- PERTURBATION 3 : LE VIP RAPIDE (UE 14) ---
# Gros trafic mais à très haute vitesse (Handover imminent ou perte de signal)
*.server.app[14].destAddresses = "ue[14]"
*.server.app[14].messageLength = 1450B
*.server.app[14].sendInterval = 0.001s
*.ue[14].mobility.typename = "GaussMarkovMobility"
*.ue[14].mobility.speed = 60mps 
*.ue[14].mobility.alpha = 0.3





